#!/usr/bin/env node

/**
 * Generate environment.prod.ts from environment variables
 * This script runs before the Angular build in Vercel
 */

const fs = require('fs');
const path = require('path');

// Get environment variables with fallbacks to current values
const apiBaseUrl = process.env.API_BASE_URL || 'https://tritrackit-api.vercel.app/api/v1';
const pusherKey = process.env.PUSHER_KEY || '525752a480ad973116be';
const pusherCluster = process.env.PUSHER_CLUSTER || 'ap1';
const socketIoUrl = process.env.SOCKET_IO_URL || 'https://socket-server-production-4c03.up.railway.app';
const idleTimeoutMinutes = process.env.IDLE_TIMEOUT_MINUTES || '30';

// Generate the environment file content
const envContent = `// This file is auto-generated by scripts/generate-env.js
// Do not edit manually - use Vercel environment variables instead

export const environment = {
  production: true,
  apiBaseUrl: "${apiBaseUrl}",
  idleTimeoutMinutes: ${idleTimeoutMinutes},
  pusher: {
    key: "${pusherKey}",
    cluster: "${pusherCluster}",
  },
  socketIo: {
    url: "${socketIoUrl}",
    options: {
      transports: ['websocket', 'polling'],
      reconnection: true,
      reconnectionDelay: 1000,
      reconnectionAttempts: 5,
      timeout: 20000,
    }
  }
};
`;

// Write to environment.prod.ts
const envPath = path.join(__dirname, '../src/environments/environment.prod.ts');
fs.writeFileSync(envPath, envContent, 'utf8');

console.log('✅ Generated environment.prod.ts from environment variables');
console.log('📋 Configuration:');
console.log(`   API Base URL: ${apiBaseUrl}`);
console.log(`   Pusher Key: ${pusherKey.substring(0, 10)}...`);
console.log(`   Pusher Cluster: ${pusherCluster}`);
console.log(`   Socket.io URL: ${socketIoUrl}`);
console.log(`   Idle Timeout: ${idleTimeoutMinutes} minutes`);

